apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "feastflow-app.fullname" . } }
  labels:
    app: { { include "feastflow-app.name" . } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { include "feastflow-app.name" . } }
  template:
    metadata:
      labels:
        app: { { include "feastflow-app.name" . } }
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.containerPort } }
            env:
              {{- range $key, $value := .Values.env }}
              - name: {{ $key }}
                value: "{{ $value }}"
              {{- end }}
            # Feature flags as environment variables
              {{- range $key, $value := .Values.featureFlags }}
              - name: {{ $key }}
                value: "{{ $value }}"
              {{- end }}
